//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCEPTOSPAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONCEPTOSPAGO()
        {
            this.PAGOes = new HashSet<PAGO>();
        }
    
        public int idConcepto { get; set; }
        public Nullable<int> nombreConcepto { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> mes { get; set; }
        public string ano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGOes { get; set; }
    }
}
