//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRUEBAEntities : DbContext
    {
        public PRUEBAEntities()
            : base("name=PRUEBAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAJA> CAJAs { get; set; }
        public virtual DbSet<CAJERO> CAJEROes { get; set; }
        public virtual DbSet<CONCEPTOSPAGO> CONCEPTOSPAGOes { get; set; }
        public virtual DbSet<EQUIVALENCIA> EQUIVALENCIAs { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<ME> MES { get; set; }
        public virtual DbSet<MONEDA> MONEDAs { get; set; }
        public virtual DbSet<PAGO> PAGOes { get; set; }
        public virtual DbSet<TBANIOS_CURSAR> TBANIOS_CURSAR { get; set; }
        public virtual DbSet<TBESTUDIANTE> TBESTUDIANTEs { get; set; }
        public virtual DbSet<TIPOCONCEPTO> TIPOCONCEPTOes { get; set; }
        public virtual DbSet<TIPODEPAGO> TIPODEPAGOes { get; set; }
    }
}
