//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int idPago { get; set; }
        public Nullable<System.DateTime> fechaTransaccion { get; set; }
        public Nullable<int> idCajero { get; set; }
        public Nullable<int> idCaja { get; set; }
        public Nullable<int> idEstudiante { get; set; }
        public string nombreEstudiante { get; set; }
        public string apellidoEstudiante { get; set; }
        public Nullable<int> conceptoPago { get; set; }
        public Nullable<int> tipoPago { get; set; }
        public Nullable<int> moneda { get; set; }
        public Nullable<decimal> pagoAbonado { get; set; }
        public Nullable<decimal> equivalencia { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<decimal> mora { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual CAJERO CAJERO { get; set; }
        public virtual CONCEPTOSPAGO CONCEPTOSPAGO { get; set; }
        public virtual ESTADO ESTADO1 { get; set; }
        public virtual MONEDA MONEDA1 { get; set; }
        public virtual TBESTUDIANTE TBESTUDIANTE { get; set; }
        public virtual TIPODEPAGO TIPODEPAGO { get; set; }
    }
}
