//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBANIOS_CURSAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBANIOS_CURSAR()
        {
            this.TBESTUDIANTEs = new HashSet<TBESTUDIANTE>();
        }
    
        public int ID_CURSO { get; set; }
        public string STR_CURSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBESTUDIANTE> TBESTUDIANTEs { get; set; }
    }
}
