//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBESTUDIANTE()
        {
            this.PAGOes = new HashSet<PAGO>();
        }
    
        public int id_estudiante { get; set; }
        public string STR_NOMBRE { get; set; }
        public string STR_APELLIDO { get; set; }
        public string STR_DIRECCION { get; set; }
        public string STR_CORREO { get; set; }
        public Nullable<System.DateTime> DT_FECHA_NAC { get; set; }
        public string STR_DOMICILIO { get; set; }
        public string STR_TELEFONO { get; set; }
        public string STR_GENERO { get; set; }
        public string CodESTUDIANTE { get; set; }
        public string COD_MINED_ESTUDIANTE { get; set; }
        public string STR_NOMBRE_PADRE { get; set; }
        public string STR_NOMBRE_MADRE { get; set; }
        public Nullable<int> numAÑO_EN_CURSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGOes { get; set; }
        public virtual TBANIOS_CURSAR TBANIOS_CURSAR { get; set; }
    }
}
